const data = {
  products: [
    {
      name: 'Mens Shirt',
      slug: 'mens-shirt',
      category: 'Shirts',
      image: 'logo192.png',
      price: 500,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.8,
      numReviews: 11,
      description: 'good shirts',
    },
    {
      name: 'Mens Pants',
      slug: 'mens-Pants',
      category: 'Pants',
      image: 'logo192.png',
      price: 50,
      countInStock: 1,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      name: 'Mens Pants',
      slug: 'mens-Pants',
      category: 'Pants',
      image: 'logo192.png',
      price: 50,
      countInStock: 1,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      name: 'Mens Pants',
      slug: 'mens-Pants',
      category: 'Pants',
      image: 'logo192.png',
      price: 50,
      countInStock: 1,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      name: 'Mens Pants',
      slug: 'mens-Pants',
      category: 'Pants',
      image: 'logo192.png',
      price: 50,
      countInStock: 1,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
  ],
};

export default data;
