const data = {
  products: [
    {
      id: '1',
      name: 'Mens Shirt',
      slug: 'mens-shirt',
      category: 'Shirts',
      image: '/shirt1.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.8,
      numReviews: 11,
      description: 'good shirts',
    },
    {
      id: '2',
      name: 'Mens Pants',
      slug: 'mens-Pants',
      category: 'Pants',
      image: '/pants1.webp',
      price: 50,
      countInStock: 0,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      id: '3',
      name: 'Mens Pants2',
      slug: 'mens-Pants-2',
      category: 'Pants',
      image: '/pants1.webp',
      price: 50,
      countInStock: 1,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      id: '4',
      name: 'Mens Pants3',
      slug: 'mens-Pants-3',
      category: 'Pants',
      image: '/pants1.webp',
      price: 50,
      countInStock: 6,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
    {
      id: '5',
      name: 'Mens Pants4',
      slug: 'mens-Pants-4',
      category: 'Pants',
      image: '/pants1.webp',
      price: 50,
      countInStock: 19,
      brand: 'Pushy',
      rating: 4,
      numReviews: 12,
      description: 'good pants',
    },
  ],
};

export default data;
